config/routes.rb
PodmedicsVictory::Application.routes.draw do

  # Static pages
  root 'static_pages#home'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/faqs', to: 'static_pages#faqs', as: 'faqs'
  get '/library', to: 'static_pages#library', as: 'library'
  get '/terms', to: 'static_pages#terms', as: 'terms'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/support', to: 'static_pages#support', as: 'support'
  get '/press', to: 'static_pages#press', as: 'press'
  get '/app', to: 'static_pages#app', as: 'app'
  get '/quiz_privacy', to: 'static_pages#quiz_privacy', as: 'quiz_privacy'
  resources :courses, only: [:index]
  resources :posts, only: [:index, :show]

  # RSS feed redirects
  match '/Podmedics/Podmedics/rss.xml' => redirect('http://feeds.feedburner.com/podmedics'), via: :get
  match '/feeds/podcasts' => redirect('http://feeds.feedburner.com/podmedics'), :as => :feed, via: :get
  match '/podcasts/rss.rss' => redirect('http://feeds.feedburner.com/podmedics'), via: :get

  # Authentication
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: :signup
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index] do
    member do
      get 'email'
      get 'move_to_gravatar'
    end
  end

  post 'unsubscribed', to: 'users#unsubscribed', as: :unsub
  get 'unsubscribe', to: 'users#unsubscribe'
  get 'unsubscribe/:unsubscribe_token', to: 'users#unsubscribe', as: :unsubscribe_token

  resources :password_resets, only: [:create, :edit, :update]

  # Omniauth
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: 'sessions#new', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  # Transactions/Stripe Events
  get ':user_id/buy', to: 'transactions#new', as: :show_buy
  post ':user_id/buy/:permalink', to: 'transactions#create', as: :buy
  get ':user_id/pickup', to: 'transactions#pickup', as: :pickup
  get '/receive_paypal', to: 'transactions#receive_paypal', as: :receive_paypal
  get ':user_id/cancel_transaction', to: 'transactions#cancel_transaction', as: :cancel_transaction
  resources :stripe_events, only: [:create]
  resources :sales, only: [:show]

  # Dashboards and admin
  match '/admin' => redirect('/admin/dashboard'), via: :get
  resource :dashboard, only: :show
  namespace :admin do
    resource :dashboard, only: :show
    resources :categories, except: :delete
    resources :specialties
    resources :questions, only: [:index]
    resources :videos, except: :delete do
      member do
        get 'move_up'
        get 'move_down'
        get 'send_notifications'
        get 'send_test_notifications'
        get 'mark_proofread'
      end
      resources :questions, except: [:index] do
        member do
          get 'mark_proofread'
        end
      end
    end
    resources :flashcards do
      member do
        get 'approve'
      end
    end
    resources :users do
      member { get 'send_1w_reminder'}
      collection { get 'remove_if_no_plan'}
    end
    resources :authors
    resources :faqs
    resources :courses
    resources :questions
    resources :products
    resources :sales, only: [:index, :show]
    resources :newsletters do
      member do
        get 'send_test'
        get 'send_newsletter'
      end
    end
    resources :posts
    resources :comments, except: [:show]
    resources :badges
    resources :quizes
    resources :notes, only: [:index, :show]
  end

  # Specialty/Video
  resources :videos, only: [:show, :index] do
    resources :flashcards, only: [:new, :create]
    resources :questions, only: :index
    get 'video', to: 'hosted_files#video', as: 'download_video'
    get 'audio', to: 'hosted_files#audio', as: 'download_audio'
    get 'slides', to: 'hosted_files#slides', as: 'download_slides'
  end
  get 'tags/:tag', to: 'videos#index', as: :tag
  match 'questions/answer', to: 'questions#answer', via: [:get, :post]
  get 'questions/result', to: 'questions#result'
  get 'questions/general', to: 'questions#general_index'
  resources :questions, only: :show

  resources :specialties, only: [:show] do
    resources :questions, controller: :specialty_questions, as: :questions
    get 'questions/load/:page', to: 'specialty_questions#load', as: :question_load
    resources :specialty_unlocks, only: [:create]
  end

  get 'specialties/:id/exam', to: 'questions#specialty_index', as: :specialty_exam

  resources :comments do
    member do
      get 'vote'
      get 'accept'
    end
  end

  resources :notes, only: [:create, :update, :show, :index] do
    get 'load', on: :member
  end
  get 'notes/specialty/:specialty_id', to: 'notes#index', as: :specialty_notes
  get 'notes/category/:category_id', to: 'notes#index', as: :category_notes

  # VimeosController
  get 'vimeos/completed', to: 'vimeos#completed', as: :vimeos_completed
  get 'vimeos/paused', to: 'vimeos#paused', as: :vimeos_paused

  # API

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :specialties
      resources :questions do
        collection do
          get 'count'
          get 'sample'
        end
      end
    end
  end

end

app/models/flashcard.rb
# == Schema Information
#
# Table name: flashcards
#
#  id             :integer          not null, primary key
#  specialty_id   :integer
#  video_id       :integer
#  views          :integer          default(0)
#  title          :string(255)
#  epidemiology   :text
#  pathology      :text
#  causes         :text
#  signs          :text
#  symptoms       :text
#  inv_cultures   :text
#  inv_bloods     :text
#  inv_imaging    :text
#  inv_scopic     :text
#  inv_functional :text
#  treat_cons     :text
#  treat_medical  :text
#  treat_surgical :text
#  created_at     :datetime
#  updated_at     :datetime
#  user_id        :integer
#  approved       :boolean          default(FALSE)
#

class Flashcard < ActiveRecord::Base

  belongs_to :video
  belongs_to :specialty
  belongs_to :user

  validates_presence_of :title
  validates_presence_of :specialty_id
  validates_presence_of :user_id
  validates_presence_of :epidemiology
  validates_presence_of :pathology
  validates_presence_of :causes
  validates_presence_of :signs
  validates_presence_of :symptoms
  validates_presence_of :inv_cultures
  validates_presence_of :inv_bloods
  validates_presence_of :inv_imaging
  validates_presence_of :inv_scopic
  validates_presence_of :inv_functional
  validates_presence_of :treat_cons
  validates_presence_of :treat_medical
  validates_presence_of :treat_surgical

  filterrific(
    default_filter_params: { sorted_by: 'approved_asc'},
    available_filters: [
      :sorted_by,
      :approved
    ]
  )

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      order("flashcards.created_at #{direction}")
    when /^title_/
      order("flashcards.title #{direction}")
    when /^approved/
      order("flashcards.approved #{direction}")
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  def self.options_for_sorted_by
    [
      ['Created', 'created_at_desc'],
      ['Title (a-z)', 'title_asc'],
      ['Approval', 'approved_asc']
    ]
  end

  def has_video?
    true if video
  end

  def is_approved?
    approved ? true : false
  end

  def approve
    update_attributes(approved: true)
    self.user.add_flashcard_credit
    UserMailer.delay.flashcard_approval(self)
  end


end

app/controllers/admin/flashcards_controller.rb
class Admin::FlashcardsController < ApplicationController
  layout 'admin_application'
  respond_to :html, :json

  def index
    @filterrific = initialize_filterrific(
      Flashcard,
      params[:filterrific],
      select_options: {
        sorted_by: Flashcard.options_for_sorted_by
      }
    ) or return

    @flashcards = @filterrific.find

    respond_to do |format|
      format.html
      format.js
    end

  rescue ActiveRecord::RecordNotFound => e
    puts "Had to reset filterrific params: #{e.message}"
    redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def new
    @flashcard = Flashcard.new
  end

  def create
    @flashcard = Flashcard.new(flashcard_params)
    if @flashcard.save
      redirect_to admin_flashcards_path, notice: 'New flashcard added'
    else
      render :new
    end
  end

  def edit
    @flashcard = Flashcard.find(params[:id])
  end

  def update
    @flashcard = Flashcard.find(params[:id])
    if @flashcard.update_attributes(flashcard_params)
      redirect_to admin_flashcards_path, notice: 'Video updated'
    else
      render :edit
    end
  end

  def approve
    @flashcard = Flashcard.find(params[:id])
    @flashcard.approve
    redirect_to admin_flashcards_path, notice: 'Flashcard approved'
  end

  def destroy
    @flashcard = Flashcard.find(params[:id])
    @flashcard.destroy
    redirect_to admin_flashcards_path, notice: 'Flashcard removed'
  end

  private

  def flashcard_params
    params.require(:flashcard).permit(:title, :video_id, :specialty_id, :epidemiology,
                                      :pathology, :causes, :signs, :symptoms, :inv_cultures,
                                      :inv_bloods, :inv_imaging, :inv_scopic, :inv_functional,
                                      :treat_cons, :treat_medical, :treat_surgical, :approved, :user_id)
  end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  layout 'user_application'

  def new
    @video = Video.friendly.find(params[:video_id])
    @flashcard = Flashcard.new
  end

  def create
    @video = Video.friendly.find(params[:video_id])
    @flashcard = Flashcard.new(flashcard_params)
    @flashcard.video_id = @video.id
    @flashcard.specialty_id = @video.specialty_id
    @flashcard.user_id = current_user.id
    if @flashcard.save
      UserMailer.delay.flashcard_submission(current_user)
      AdminMailer.delay.flashcard_submission(@flashcard)
      redirect_to @video, notice: 'Thank you. Your flashcard has been submitted and will be reviewed.'
    else
      flash.now[:error] = 'Please review the form'
      render :new
    end
  end

  private

  def flashcard_params
    params.require(:flashcard).permit(:title, :video_id, :specialty_id, :epidemiology,
                                      :pathology, :causes, :signs, :symptoms, :inv_cultures,
                                      :inv_bloods, :inv_imaging, :inv_scopic, :inv_functional,
                                      :treat_cons, :treat_medical, :treat_surgical, :user_id)
  end

end

app/views/admin/flashcards/_flashcard.html.erb
<tr id="filterrific_results">
  <td><%= flashcard.id %></td>
  <td><%= flashcard.created_at %></td>
  <td><%= flashcard.title %></td>
  <td>
    <% if flashcard.video %>
      <%= link_to flashcard.video.title, admin_video_path(flashcard.video) %>
    <% end %>
  </td>
  <td><%= link_to flashcard.specialty.name, admin_specialty_path(flashcard.specialty) %></td>
  <td>
    <% if flashcard.user %>
        <%= link_to flashcard.user.name, admin_user_path(flashcard.user) %>
    <% else %>
        No user set
    <% end %>
  </td>
  <td><%= flashcard.is_approved? %></td>
  <td>
    <ul class="actions">
      <% if flashcard.video %>
        <li><%= link_to 'Preview', video_path(flashcard.video) %></li>
      <% end %>
      <li><%= link_to 'Edit', edit_admin_flashcard_path(flashcard) %></li>
      <li>
        <% unless flashcard.is_approved? %>
            <%= link_to 'Approve', approve_admin_flashcard_path(flashcard) %>
        <% end %>
      </li>
      <li><%= link_to 'Remove', admin_flashcard_path(flashcard), method: :delete, data: { confirm: 'Are you sure?'} %></li>
    </ul>
  </td>
</tr>

app/views/admin/flashcards/_form.html.erb
<div class="row form-wrapper">
  <div class="col-md-6">
    <%= simple_form_for [:admin, @flashcard] do |f| %>
        <%= f.error_notification %>
        <%= f.input :title %>
        <%= f.input :approved %>
        <%= f.association :video, collection: Video.all.order(:title), prompt: 'Select a video', include_blank: true %>
        <%= f.association :specialty, collection: Specialty.all.order(:name), prompt: 'Select a specialty' %>
        <h2>General</h2>
        <%= f.input :epidemiology, as: :text, label: 'Epidemiology' %>
        <%= f.input :pathology, as: :text, label: 'Pathology' %>
        <%= f.input :causes, as: :text, label: 'Top three causes' %>
        <h2>Clinical Features</h2>
        <%= f.input :symptoms, as: :text, label: 'Symptoms (general and specific)' %>
        <%= f.input :signs, as: :text, label: 'Signs (general and specific)' %>
        <h2>Investigations</h2>
        <%= f.input :inv_cultures, as: :text, label: 'Investigations: Cultures' %>
        <%= f.input :inv_bloods, as: :text, label: 'Investigations: Bloods' %>
        <%= f.input :inv_imaging, as: :text, label: 'Investigations: Imaging' %>
        <%= f.input :inv_scopic, as: :text, label: 'Investigations: Scopic/Biopsy' %>
        <%= f.input :inv_functional, as: :text, label: 'Investigations: Functional' %>
        <h2>Treatment</h2>
        <%= f.input :treat_cons, as: :text, label: 'Conservative' %>
        <%= f.input :treat_medical, as: :text, label: 'Medical' %>
        <%= f.input :treat_surgical, as: :text, label: 'Surgical' %>
        <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/admin/flashcards/edit.html.erb
<div class="row header">
  <div class="col-md-12">
    <h3>Edit Flashcard</h3>
    <br/>
    <%= link_to 'View all', admin_flashcards_path %>
  </div>
</div>

<%= render 'form' %>

app/views/admin/flashcards/index.html.erb
<div class="row header">
  <h3>Flashcards</h3>
  <div class="col-md-10 col-sm-10 col-xs-10 pull-right">
    <%= link_to "New flashcard", new_admin_flashcard_path, class: 'btn-flat success pull-right' %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit'} do |f| %>
      <div>
        <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
      </div>
      <div>
        <%= link_to 'Reset filters', reset_filterrific_url %>
      </div>
      <%= f.submit 'Filter' %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="table-wrapper">
      <table class="table table-hover table-striped" border="0">
        <thead>
            <tr>
              <th>#</th>
              <th>Created at</th>
              <th>Title</th>
              <th>Video</th>
              <th>Specialty</th>
              <th>User</th>
              <th>Approved?</th>
              <th></th>
            </tr>
        </thead>
        <tbody>
            <%= render @flashcards %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/flashcards/new.html.erb
<div class="row header">
  <div class="col-md-12">
    <h3>New Flashcard</h3>
  </div>
</div>

<%= render 'form' %>