config/routes.rb
PodmedicsVictory::Application.routes.draw do

  # Static pages
  root 'static_pages#home'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/faqs', to: 'static_pages#faqs', as: 'faqs'
  get '/library', to: 'static_pages#library', as: 'library'
  get '/terms', to: 'static_pages#terms', as: 'terms'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/support', to: 'static_pages#support', as: 'support'
  get '/press', to: 'static_pages#press', as: 'press'
  get '/app', to: 'static_pages#app', as: 'app'
  get '/quiz_privacy', to: 'static_pages#quiz_privacy', as: 'quiz_privacy'
  resources :courses, only: [:index]
  resources :posts, only: [:index, :show]

  # RSS feed redirects
  match '/Podmedics/Podmedics/rss.xml' => redirect('http://feeds.feedburner.com/podmedics'), via: :get
  match '/feeds/podcasts' => redirect('http://feeds.feedburner.com/podmedics'), :as => :feed, via: :get
  match '/podcasts/rss.rss' => redirect('http://feeds.feedburner.com/podmedics'), via: :get

  # Authentication
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: :signup
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index] do
    member do
      get 'email'
      get 'move_to_gravatar'
    end
  end

  post 'unsubscribed', to: 'users#unsubscribed', as: :unsub
  get 'unsubscribe', to: 'users#unsubscribe'
  get 'unsubscribe/:unsubscribe_token', to: 'users#unsubscribe', as: :unsubscribe_token

  resources :password_resets, only: [:create, :edit, :update]

  # Omniauth
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: 'sessions#new', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  # Transactions/Stripe Events
  get ':user_id/buy', to: 'transactions#new', as: :show_buy
  post ':user_id/buy/:permalink', to: 'transactions#create', as: :buy
  get ':user_id/pickup', to: 'transactions#pickup', as: :pickup
  get '/receive_paypal', to: 'transactions#receive_paypal', as: :receive_paypal
  get ':user_id/cancel_transaction', to: 'transactions#cancel_transaction', as: :cancel_transaction
  resources :stripe_events, only: [:create]
  resources :sales, only: [:show]

  # Dashboards and admin
  match '/admin' => redirect('/admin/dashboard'), via: :get
  resource :dashboard, only: :show
  namespace :admin do
    resource :dashboard, only: :show
    resources :categories, except: :delete
    resources :specialties
    resources :questions, only: [:index]
    resources :videos, except: :delete do
      member do
        get 'move_up'
        get 'move_down'
        get 'send_notifications'
        get 'send_test_notifications'
        get 'mark_proofread'
      end
      resources :questions, except: [:index] do
        member do
          get 'mark_proofread'
        end
      end
    end
    resources :flashcards do
      member do
        get 'approve'
      end
    end
    resources :users do
      member { get 'send_1w_reminder'}
      collection { get 'remove_if_no_plan'}
    end
    resources :authors
    resources :faqs
    resources :courses
    resources :questions
    resources :products
    resources :sales, only: [:index, :show]
    resources :newsletters do
      member do
        get 'send_test'
        get 'send_newsletter'
      end
    end
    resources :posts
    resources :comments, except: [:show]
    resources :badges
    resources :quizes
    resources :notes, only: [:index, :show]
  end

  # Specialty/Video
  resources :videos, only: [:show, :index] do
    resources :flashcards, only: [:new, :create]
    resources :questions, only: :index
    get 'video', to: 'hosted_files#video', as: 'download_video'
    get 'audio', to: 'hosted_files#audio', as: 'download_audio'
    get 'slides', to: 'hosted_files#slides', as: 'download_slides'
  end
  get 'tags/:tag', to: 'videos#index', as: :tag
  match 'questions/answer', to: 'questions#answer', via: [:get, :post]
  get 'questions/result', to: 'questions#result'
  get 'questions/general', to: 'questions#general_index'
  resources :questions, only: :show

  resources :specialties, only: [:show] do
    resources :questions, controller: :specialty_questions, as: :questions
    get 'questions/load/:page', to: 'specialty_questions#load', as: :question_load
    resources :specialty_unlocks, only: [:create]
  end

  get 'specialties/:id/exam', to: 'questions#specialty_index', as: :specialty_exam

  resources :comments do
    member do
      get 'vote'
      get 'accept'
    end
  end

  resources :notes, only: [:create, :update, :show, :index] do
    get 'load', on: :member
  end
  get 'notes/specialty/:specialty_id', to: 'notes#index', as: :specialty_notes
  get 'notes/category/:category_id', to: 'notes#index', as: :category_notes

  # VimeosController
  get 'vimeos/completed', to: 'vimeos#completed', as: :vimeos_completed
  get 'vimeos/paused', to: 'vimeos#paused', as: :vimeos_paused

  # API

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :specialties
      resources :questions do
        collection do
          get 'count'
          get 'sample'
        end
      end
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout :conditional_layout, only: [:support, :about, :terms, :contact]

  def home
    redirect_to dashboard_path if current_user && current_user.has_selected_plan?
    @paid_6 = Product.where(permalink: 'paid6').first
    @paid_12 = Product.where(permalink: 'paid12').first
  end

  def about
  end

  def faqs
    @faqs = Faq.public
  end

  def library
    @categories = Category.order(:id).select(:name, :id, :updated_at)
  end

  def terms
  end

  def contact
  end

  def support
    @faqs = Faq.all
    render :faqs
  end

  def press
  end

  def app
  end

  def quiz_privacy
  end

  private

    def conditional_layout
      current_user ? 'user_application' : 'application'
    end

end

app/views/static_pages/about.html.erb
<%= content_for(:title) { "Podmedics | About"} %>

<div class="inner about_page_inner">
  <div class="sub_heading_wrapper">
    <h1>About Podmedics</h1>
  </div>

  <div class="page">
    <div class="about_left_column">
      <p>Podmedics was founded in 2007 with the aim of making revision more productive, more effective and more enjoyable.  We all know how painful it can be to tackle a tough chapter in a hefty medical text, so we thought, “why not present core material via video and audio?” And that’s exactly what we did. </p>
      <p>We began producing our early tutorials using some fairly basic technology, and they proved so popular we were soon bombarded with requests for more. Today, Podmedics offers more than 200 professionally produced videos presented by doctors, medical students and a diverse range of experienced healthcare professionals.</p>
      <p>Our vision has always been to deliver high-quality productions that are affordable and accessible to all. So we’re continually expanding our library to cover a growing number of specialist topics. And we’re always working hard to develop new features, like intelligent tutorial prompts and our easy-to-use note-taking system. </p>
      <p>If there are any new features you’d like to see, or any topics you’d like us to cover, we’d love to hear from you. Email your suggestions to <a href="mailto:contact@podmedics.com">contact@podmedics.com</a></p>
      <div class="about_column_divide"></div>

      <div class="founder_block">

        <div class="founder_icon"><img src="<%=asset_path "ed_founder_icon.png"%>" width="142" height="142" alt=""/></div>

        <h1>Dr Ed Wallitt</h1>
        <p class="founder_sub_title">Founder</p>
        <p>Ed Wallitt is the founder and director of Podmedics. He qualified from Imperial College School of Medicine in 2008 and worked for four years as a junior doctor in West London - achieving a place on the prestigious St Mary's GP Vocational Training Scheme. He now runs the medical IT consultancy side of Podmedics, providing high quality software consultancy and development services to NHS Trusts and healthcare start-ups in the UK.</p>

        <div class="founder_social_icons">
          <a href="https://twitter.com/podmedicsed" class="twitter_footer_icon"></a>
          <a href="https://en-gb.facebook.com/pages/Podmedics/143536736080" class="fb_footer_icon"></a>
        </div>

      </div>
    </div>

    <div class="about_right_column">
      <p class="about_right_column_title">THE LECTURERS</p>
      <p>Dr Stevan Wing <span>- General Medicine</span></p>
      <p>Mr Michael Raffery <span>- General Surgery</span></p>
      <p>Mr Jonny Manley <span>- General Surgery</span></p>
      <p>Dr Rashmi Patel <span>- General Medicine and Epidemiology</span></p>
      <p>Dr Tamara Keith <span>- Paediatrics</span></p>
      <p>Mr Bernard Ho <span>- Dermatology</span></p>
      <p>Ms Vicky Pyne <span>- Lecturer/Editor</span></p>
      <p>Mr Shiv Chopra <span>- Paediatrics</span></p>
      <p>Dr Mazin Alsaffar <span>- Anatomy</span></p>
      <p>Dr Jean Lee <span>- General Medicine and Examinations</span></p>
      <p>Dr Jemma Theivendran <span>- Psychiatry</span></p>
      <p>Dr Kathryn Wallitt <span>- Radiology</span></p>
      <p>Dr James Burn <span>- Radiology</span></p>
      <p>Dr Cosmo Scurr <span>- Emergency Care</span></p>
      <p>Miss Kenga Sivarajah <span>- Obstetrics and Gynaecology</span></p>
      <p>Dr Tom Hamptom <span>- Neurology</span></p>
      <p>Dr Shireen Emadossadaty <span>- Anaesthetics</span></p>
      <p>Dr Junaid Fukuta <span>- General Medicine</span></p>
      <p>Dr Chad Chang <span> - Plastic Surgery</span></p>
    </div>

  </div>

</div>

<%= content_for :footer do %>
  <div class="inline_footer_wrapper about_page_footer">
    <%= render 'footer' %>
  </div>
<% end %>

app/views/static_pages/app.html.erb
<div class="quiz_app_header">
  <h1>The Podmedics Free Quiz App</h1>
  <p>Test yourself with thousands of medical questions wherever you are.</p>
  <div class="quiz_appstore_buttons">
    <a href="https://itunes.apple.com/gb/app/podmedics/id651077752?mt=8" class="app_store_button">Available on the App Store</a>
    <a href="https://play.google.com/store/apps/details?id=com.ionicframework.podmedicsquiz794507" class="google_play_button">Available on Google Play</a>
  </div>
  <div class="quiz_app_header_image"></div>
</div>

<div class="quiz_app_section_one">
  <div class="quiz_app_section_one_wrapper">
    <div class="quiz_app_section_one_left_column"></div>
    <div class="quiz_app_section_one_right_column">
      <h2>Learn and test yourself on the go.</h2>
      <p>Our new app gives you all our great questions to answer on the go. Either answer random questions for a quick session, or create a custom set of questions for any specialty.</p>
    </div>
  </div>
</div>

<!--
<div class="quiz_app_section_two">
  <div class="quiz_app_section_two_wrapper">
    <h2>Just some of the benefits of our app</h2>
    <p>Test yourself with thousands of medical related questions wherever you are.</p>


    <ul>
      <li>
        <h3>Thousands of Questions</h3>
        <p>Nunc ac mauris imperdiet, porta tellus non, efficitur libero. Donec varius nec lorem vitae venenatis. Etiam cursus blandit felis eu molestie.</p>
      </li>

      <li>
        <h3>Thousands of Questions</h3>
        <p>Nunc ac mauris imperdiet, porta tellus non, efficitur libero. Donec varius nec lorem vitae venenatis. Etiam cursus blandit felis eu molestie.</p>
      </li>

      <li>
        <h3>Thousands of Questions</h3>
        <p>Nunc ac mauris imperdiet, porta tellus non, efficitur libero. Donec varius nec lorem vitae venenatis. Etiam cursus blandit felis eu molestie.</p>
      </li>

      <li>
        <h3>Thousands of Questions</h3>
        <p>Nunc ac mauris imperdiet, porta tellus non, efficitur libero. Donec varius nec lorem vitae venenatis. Etiam cursus blandit felis eu molestie.</p>
      </li>

      <li>
        <h3>Thousands of Questions</h3>
        <p>Nunc ac mauris imperdiet, porta tellus non, efficitur libero. Donec varius nec lorem vitae venenatis. Etiam cursus blandit felis eu molestie.</p>
      </li>

      <li>
        <h3>Thousands of Questions</h3>
        <p>Nunc ac mauris imperdiet, porta tellus non, efficitur libero. Donec varius nec lorem vitae venenatis. Etiam cursus blandit felis eu molestie.</p>
      </li>
    </ul>
  </div>
</div>
-->

<div class="quiz_app_section_three">
  <h2>Available for free on iPhone &amp; Android</h2>
 <p>Test yourself with thousands of medical questions wherever you are.</p>
  <div class="quiz_appstore_buttons">
    <a href="https://itunes.apple.com/gb/app/podmedics/id651077752?mt=8" class="app_store_button">Available on the App Store</a>
    <a href="https://play.google.com/store/apps/details?id=com.ionicframework.podmedicsquiz794507" class="google_play_button">Available on Google Play</a>
  </div>
  <div class="quiz_app_section_three_devices_wrapper">
    <div class="quiz_app_section_three_iphone"></div>
    <div class="quiz_app_section_three_android"></div>
  </div>
</div>


<%= content_for :footer do %>
  <div class="quiz_app_footer">
    <%= render 'footer' %>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<%= content_for(:title) { "Podmedics | Contact"} %>

<div class="inner login_page_inner">

  <div class="page">
    <div class="inner_page_padding">

      <div class="text_based_page">
        <p>If you have any questions or issues do not hesitate to get in touch. We would love to hear from you.</p>
        <p class="get_in_touch_title">Ways to get in touch</p>

        <p class="about_buttons">
          <a href="mailto:contact@podmedics.com" class="podmedcis_button green mail_button">Drop us an Email</a>
          <a href="http://twitter.com/podmedics" class="twitter_social_button" target="_blank">Find us on Twitter</a>
          <a href="http://en-gb.facebook.com/pages/Podmedics/143536736080" class="fb_social_button" target="_blank">Find us on Facebook</a></p>
      </div>
    </div>
  </div>

</div>

<%= content_for :footer do %>
  <div class="inline_footer_wrapper login_page_footer">
    <%= render 'footer' %>
  </div>
<% end %>

app/views/static_pages/faqs.html.erb
<%= content_for(:title) { "Podmedics | FAQs"} %>

<div class="inner">
  <div class="sub_heading_wrapper">
    <h1>Frequently Asked Questions</h1>
  </div>

  <div class="page">
    <div class="inner_page_padding">
      <div class="faq_wrapper">
        <%= render @faqs %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<%= content_for(:title) { "Podmedics | Medical Revision"} %>
<div class="mobile_navigation">
  <%= link_to 'home', root_path , class: "nav-home" %>
  <%= link_to 'videos', library_path , class:"nav-lectures" %>
  <a href="#questions">Questions</a>
  <%= link_to "quiz app", app_path %>
  <%= link_to 'about', about_path , class: "nav-about" %>
  <%= link_to "Blog", posts_path %>
  <%= link_to 'faqs',  faqs_path , class: "nav-faqs" %>
  <%= link_to "login", login_path , class: "nav-login" %>
  <%= link_to "sign up", signup_path , class: "nav-signup" %>
</div>

<div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right" id="cbp-spmenu-s2">
  <div class="inner_menu_wrapper">
    <div class="main_nav_wrapper" id="main_navigation">
      <%= link_to 'home', root_path , class: "nav-home" %>
      <%= link_to 'our lectures', library_path , class:"nav-lectures" %>
      <%= link_to 'about', about_path , class: "nav-about" %>
      <%= link_to 'faqs',  faqs_path , class: "nav-faqs" %>
      <%= link_to "login", login_path , class: "nav-login" %>
      <%= link_to "sign up", signup_path , class: "nav-signup" %>
      <p class="slideout_nav_podmedics_icon"></p>
    </div>
  </div>
</div>
<div class="navigation_outer_overlay"></div>

<div class="home_page_header">

  <%= link_to '', root_path , class: "podmedics_home_icon" %>

  <a href="javascript:;" class="mobile_nav_icon">
    <p></p>
    <p></p>
    <p></p>
  </a>

  <div class="home_navigation">
    <%= link_to 'home', root_path , class: "nav-home" %>
    <%= link_to 'videos', library_path , class:"nav-lectures" %>
    <a href="#questions">Questions</a>
    <%= link_to "quiz app", app_path %>

    <div class="home_drop_down_wrapper">
      <a href="javascript:;" class="home_drop_down_parent_link">
        <p>About</p>
        <p class="home_dropdown_icon"></p>
      </a>
      <div class="home_drop_down">
        <div class="home_drop_down_inner">
          <%= link_to 'about', about_path , class: "nav-about" %>
          <%= link_to "Blog", posts_path %>
          <%= link_to 'faqs',  faqs_path , class: "nav-faqs" %>
        </div>
      </div>
    </div>

    <%= link_to "login", login_path , class: "nav-login" %>
    <%= link_to "sign up", signup_path , class: "nav-signup" %>
  </div>

    <% content_for :navigation do %>
     <span></span>
    <% end %>

  <div class="inner_home_header">
    <h1>Quality Medical Revision As It Should Be. <span class="free_span">Free</span>.</h1>
    <p class="podmedics_intro_message">Watch 100s of beautifully made medical revision videos and answer 1000s of questions that are tailored specifically to you</p>
    <div class="inner_home_header_action_buttons">
      <a href="/signup" class="red_button home_action_button">Sign Up Now (it's 100% free)</a>
    </div>
  </div>
</div>

<div class="home_section_video">
  <div class="home_section_inner_wrapper">
    <div class="home_top_section_left_column">
      <h2>High Quality Video Tutorials</h2>
      <p>Podmedics has over 200 medical revision videos that help you approach revising for your exams in a concise and consistant way.</p>
      <div class="home_video_action_buttons">
        <%= link_to "Explore our full video library", library_path, class: 'red_button' %>
      </div>
      <p class="home_feeds_info_wrapper">Follow our <a href="http://feeds.feedburner.com/podmedics" target="_blank">RSS feed</a> of free episodes or subscribe on <a href="https://itunes.apple.com/gb/podcast/podmedics/id262862893?mt=2" target="_blank">iTunes</a></p>
    </div>
    <div class="home_top_section_right_column">
      <div class="index_video_wrapper">
        <iframe src="//fast.wistia.net/embed/iframe/vujivsaamt" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="640" height="360"></iframe>
      </div>
    </div>
  </div>
</div>

<div class="home_section_questions" id="questions">
  <div class="home_section_inner_wrapper">
    <div class="home_top_section_left_column">
      <h2>Relevant Questions</h2>
      <p>Our videos are matched by great questions and explanations that let you test yourself on individual videos/topics or by the specialty you are revising.</p>
    </div>
    <div class="home_top_section_right_column questions_right_column_wrapper right_column">
      <div class="index_questions_wrapper">
      <div class="try_questions_sketch"></div>
          <div ng-app='TrialQuestionsApp'>
            <div ng-controller='TrialQuestionsController as vm'>
              <div class="question" ng-show="vm.firstQuestionAvailable">
                <div class="index_questions_header">
                  <div ng-bind-html="vm.currentQuestion.stem" class="questions_header_padding"></div>
                </div>

                <div class="index_questions_block">

                  <ul ng-class="{ 'showAnswer' : vm.showAnswer }">
                    <li ng-repeat="answer in vm.currentQuestion.answers" ng-class="{ 'correct' : vm.isCorrect(answer), 'incorrect' : answer.selectedAndIncorrect, 'notSelectedAndIncorrect' : answer.notSelectedAndIncorrect }">
                      <a ng-click="vm.selectedAnswer(answer)">{{answer.text}}</a>
                    </li>
                  </ul>

                  <div class="answer" ng-show="vm.showAnswer">
                    <div ng-bind-html="vm.currentQuestion.explanation"></div>
                    <div class="index_question_next_button">
                      <a ng-click="vm.nextQuestion()" class="red_button">Next Question</a>
                    </div>
                  </div>
                </div>
              </div>

              <div class="end_questions" ng-show="vm.questionsEnded">
                <h3>You have finished all the trial questions.</h3>
                <p><%= link_to "Sign Up to access more", signup_path , class: "signup_button" %></p>
                <a ng-click="vm.startAgain()" class="red_button">Start again</a>
              </div>

            </div>
          </div>
      </div>
    </div>
  </div>
</div>

<div class="home_section">
  <div class="home_section_one">
    <h2>What is Podmedics</h2>
    <p>Who we are &amp; what we do</p>
    <div class="home_section_one_block">
      <div class="section_one_column">
        <h3>About Podmedics</h3>
        <p>Podmedics has over 200 videos that condense key facts and practical techniques into succinct tutorials, making it easier to absorb and retain essential material. </p>
      </div>
      <div class="icon podmedics_icon"></div>
    </div>

    <div class="home_section_one_block">
      <div class="section_one_column">
        <h3>Medical Video Tutorials</h3>
        <p>Over 200 concise medical tutorials covering all specialist areas. Available via download or streaming.</p>
      </div>
      <div class="icon lecture_block"></div>
    </div>

    <div class="home_section_one_block">
      <div class="section_one_column">
        <h3>Performance Monitoring and Suggestions</h3>
        <p>Your personal dashboard gives you an instant snapshot of your progress… videos watched, online exams passed, questions successfully answered.</p>
      </div>
      <div class="icon questions_block"></div>
    </div>

    <div class="home_section_one_block">
      <div class="section_one_column">
        <h3>Earn badges and show off your skills</h3>
        <p>Win recognition and earn a Podmedics promotion by watching videos, answering questions and contributing to the community.</p>
      </div>
      <div class="icon badges_block"></div>
    </div>
  </div>
</div>

<div class="home_section_two">
  <div class="home_section_inner_wrapper">
    <div class="left_column">
      <h2>Personalised prompts</h2>
      <p>By analysing which tutorials you watch and how you perform in the post-video questions, your personal dashboard will suggest related videos to accelerate your progress.</p>
    </div>
  </div>

  <div class="browser_window"></div>
</div>

<div class="home_section_three">
  <div class="home_section_three_header">
    <h2>Works great on any mobile device</h2>
    <p>Podmedics is configured to work perfectly on any mobile device. We even adjust the size of video files to minimise your data usage.</p>
  </div>

  <div class="home_section_three_devices_wrapper">
    <div class="home_section_three_iphone"></div>
    <div class="home_section_three_ipad"></div>
  </div>
</div>


<div class="home_section_four">
  <div class="browser_window"></div>
  <div class="home_section_inner_wrapper">
    <div class="right_column">
      <h2>Easy-to-access revision notes</h2>
      <p>Make revision notes on-screen and recall them in an instant.</p>
    </div>
  </div>
</div>

<div class="oxford_uni_section">
  <div class="oxford_uni_left_column">
    <div class="oxford_uni_logo"></div>
  </div>

  <div class="oxford_uni_right_column">
    <div class="oxford_uni_text">
      <h3>Delivered by and trusted by the best.</h3>
      <p>Podmedics tutorials are so popular that we’ve been commissioned by Oxford University Press and Elsevier (publishers of Kumar and Clark) to produce a range of videos for wider publication. And many of them are available right here!</p>
    </div>
  </div>

</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
    mixpanel.track('Hit Landing Page');
  });
</script>

app/views/static_pages/library.html.erb
<%= content_for(:title) { "Podmedics | Library"} %>

<div class="inner">
  <div class="sub_heading_wrapper">
    <h1>Library</h1>
  </div>
  <div class="page">
    <div class="library_welcome">
      Feel free to explore our video library. <span class="podmedics_red">Episodes in red</span> can be watched in full right here on this page!
      Please <%= link_to 'Sign up', new_user_path %> to get access to all our videos.
    </div>
    <div class="inner_page_padding library_page_inner_spacing">
      <% @categories.each do |category| %>
        <% cache category do %>
          <a href="javascript:;" class="library_button" id="library_<%= category.name.downcase  %>_link">
            <h2><%= category.name %></h2>
            <p class="inline_arrow_icon"></p>
            <p class="library_count"><%= pluralize(category.video_count, 'Lecture') %></p>
          </a>

          <div class="library_tab" id="<%= category.name %>_tab">
            <% category.specialties.order(:name).each do |specialty| %>
              <% cache specialty do %>
                <div class="library_column">
                  <p><%= specialty.name.upcase %></p>
                  <% specialty.videos.order('title').each do |video| %>
                    <% cache video do %>
                      <% if video.preview %>
                        <p class="active_library_link">
                          <%= link_to video.title, "https://vimeo.com/#{video.vimeo_identifier}.mp4", class: 'fresco', data: { :'fresco-group' => 'library_videos'} %>
                        </p>
                      <% else %>
                        <p><%= video.title %></p>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/press.html.erb
<%= content_for(:title) { "Podmedics | Press"} %>

<div class="inner about_page_inner">
  <div class="sub_heading_wrapper">
    <h1>Press Kit</h1>
  </div>

  <div class="page">
    <div class="press_kit_header">
      <p>Thanks for visiting our press kit page! If you are planning on writing about or promoting Podmedics you should find all the assets and images that you need right here.</p>
      <p>If you want to chat with us please drop us an email at <%= mail_to 'contact@podmedics.com' %>, or contact us via Twitter through <%= link_to '@podmedics', 'https://twitter.com/podmedics', target: '_blank' %>.</p>
    </div>

    <div class="press_kit_blocks">
      <h2>Press Kit Images</h2>
      <p>Click on the blocks below to download, or you can download our entire press kit below.</p>

      <div class="press_kit_block_inner">
        <div class="press_kit_block_one">
          <a href="http://podmedics-assets.s3.amazonaws.com/press/podmedics-press-kit-web.zip" class="press_kit_block_image_one"></a>
          <p>Browser Windows</p>
        </div>

        <div class="press_kit_block_two">
          <a href="http://podmedics-assets.s3.amazonaws.com/press/podmedics-press-kit-devices.zip" class="press_kit_block_image_two"></a>
          <p>Device Mockups</p>
        </div>

        <div class="press_kit_block_three">
          <a href="http://podmedics-assets.s3.amazonaws.com/press/podmedics-press-kit-icons.zip" class="press_kit_block_image_three"></a>
          <p>Podmedics Icons</p>
        </div>

      </div>

    </div>

    <div class="press_kit_lower_blocks">
      <div class="press_kit_lower_block_inner">
        <h3>Company Colours</h3>
        <p>These are our primary comany colours</p>
        <div class="press_kit_lower_colour_blocks_inner">
          <div class="colour_block red_press_kit_block">#fa3f52</div>
          <div class="colour_block grey_press_kit_block">#F8F8F8</div>
          <div class="colour_block green_press_kit_block">#8CDE7F</div>
        </div>
      </div>


    </div>
    <div class="press_kit_lower_blocks">
      <div class="press_kit_lower_block_inner">
        <h3>Full Press Kit</h3>
        <a href="http://podmedics-assets.s3.amazonaws.com/press/podmedics-press-kit.zip" class="podmedcis_button">Download our full Press Kit  (6.9mb)</a>
      </div>
    </div>

  </div>

</div>

<%= content_for :footer do %>
  <div class="inline_footer_wrapper about_page_footer">
    <%= render 'footer' %>
  </div>
<% end %>

app/views/static_pages/support.html.erb
<%= content_for(:title) { "Podmedics | Support"} %>

<div class="inner">
  <div class="sub_heading_wrapper">
    <h1>Support</h1>
  </div>

  <div class="page">
    <div class="inner_page_padding">
      <p class="lecture_questions_sub_title"></p>

      <% @faqs.each do |faq| %>
        <a href="javascript:;" class="library_button">
          <h2><%= faq.title %></h2>
          <p class="inline_arrow_icon"></p>
        </a>
        <div class="library_tab">
          <div class="faq_inner"><%= faq.content %></div>
        </div>
      <% end %>

    </div>
  </div>
</div>