config/routes.rb
PodmedicsVictory::Application.routes.draw do

  # Static pages
  root 'static_pages#home'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/faqs', to: 'static_pages#faqs', as: 'faqs'
  get '/library', to: 'static_pages#library', as: 'library'
  get '/terms', to: 'static_pages#terms', as: 'terms'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/support', to: 'static_pages#support', as: 'support'
  get '/press', to: 'static_pages#press', as: 'press'
  get '/app', to: 'static_pages#app', as: 'app'
  get '/quiz_privacy', to: 'static_pages#quiz_privacy', as: 'quiz_privacy'
  resources :courses, only: [:index]
  resources :posts, only: [:index, :show]

  # RSS feed redirects
  match '/Podmedics/Podmedics/rss.xml' => redirect('http://feeds.feedburner.com/podmedics'), via: :get
  match '/feeds/podcasts' => redirect('http://feeds.feedburner.com/podmedics'), :as => :feed, via: :get
  match '/podcasts/rss.rss' => redirect('http://feeds.feedburner.com/podmedics'), via: :get

  # Authentication
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: :signup
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index] do
    member do
      get 'email'
      get 'move_to_gravatar'
    end
  end

  post 'unsubscribed', to: 'users#unsubscribed', as: :unsub
  get 'unsubscribe', to: 'users#unsubscribe'
  get 'unsubscribe/:unsubscribe_token', to: 'users#unsubscribe', as: :unsubscribe_token

  resources :password_resets, only: [:create, :edit, :update]

  # Omniauth
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: 'sessions#new', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  # Transactions/Stripe Events
  get ':user_id/buy', to: 'transactions#new', as: :show_buy
  post ':user_id/buy/:permalink', to: 'transactions#create', as: :buy
  get ':user_id/pickup', to: 'transactions#pickup', as: :pickup
  get '/receive_paypal', to: 'transactions#receive_paypal', as: :receive_paypal
  get ':user_id/cancel_transaction', to: 'transactions#cancel_transaction', as: :cancel_transaction
  resources :stripe_events, only: [:create]
  resources :sales, only: [:show]

  # Dashboards and admin
  match '/admin' => redirect('/admin/dashboard'), via: :get
  resource :dashboard, only: :show
  namespace :admin do
    resource :dashboard, only: :show
    resources :categories, except: :delete
    resources :specialties
    resources :questions, only: [:index]
    resources :videos, except: :delete do
      member do
        get 'move_up'
        get 'move_down'
        get 'send_notifications'
        get 'send_test_notifications'
        get 'mark_proofread'
      end
      resources :questions, except: [:index] do
        member do
          get 'mark_proofread'
        end
      end
    end
    resources :flashcards do
      member do
        get 'approve'
      end
    end
    resources :users do
      member { get 'send_1w_reminder'}
      collection { get 'remove_if_no_plan'}
    end
    resources :authors
    resources :faqs
    resources :courses
    resources :questions
    resources :products
    resources :sales, only: [:index, :show]
    resources :newsletters do
      member do
        get 'send_test'
        get 'send_newsletter'
      end
    end
    resources :posts
    resources :comments, except: [:show]
    resources :badges
    resources :quizes
    resources :notes, only: [:index, :show]
  end

  # Specialty/Video
  resources :videos, only: [:show, :index] do
    resources :flashcards, only: [:new, :create]
    resources :questions, only: :index
    get 'video', to: 'hosted_files#video', as: 'download_video'
    get 'audio', to: 'hosted_files#audio', as: 'download_audio'
    get 'slides', to: 'hosted_files#slides', as: 'download_slides'
  end
  get 'tags/:tag', to: 'videos#index', as: :tag
  match 'questions/answer', to: 'questions#answer', via: [:get, :post]
  get 'questions/result', to: 'questions#result'
  get 'questions/general', to: 'questions#general_index'
  resources :questions, only: :show

  resources :specialties, only: [:show] do
    resources :questions, controller: :specialty_questions, as: :questions
    get 'questions/load/:page', to: 'specialty_questions#load', as: :question_load
    resources :specialty_unlocks, only: [:create]
  end

  get 'specialties/:id/exam', to: 'questions#specialty_index', as: :specialty_exam

  resources :comments do
    member do
      get 'vote'
      get 'accept'
    end
  end

  resources :notes, only: [:create, :update, :show, :index] do
    get 'load', on: :member
  end
  get 'notes/specialty/:specialty_id', to: 'notes#index', as: :specialty_notes
  get 'notes/category/:category_id', to: 'notes#index', as: :category_notes

  # VimeosController
  get 'vimeos/completed', to: 'vimeos#completed', as: :vimeos_completed
  get 'vimeos/paused', to: 'vimeos#paused', as: :vimeos_paused

  # API

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :specialties
      resources :questions do
        collection do
          get 'count'
          get 'sample'
        end
      end
    end
  end

end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id                   :integer          not null, primary key
#  title                :string(255)
#  description          :text
#  specialty_id         :integer
#  vimeo_identifier     :string(255)
#  duration             :integer
#  created_at           :datetime
#  updated_at           :datetime
#  preview              :boolean          default(FALSE)
#  slug                 :string(255)
#  speaker_name         :string(255)
#  views                :integer          default(0)
#  file_name            :string(255)
#  questions_count      :integer          default(0), not null
#  position             :integer
#  author_id            :integer
#  slide_download_count :integer
#  audio_download_count :integer
#  video_download_count :integer
#  proofread            :boolean          default(FALSE)
#  has_slides           :boolean          default(TRUE)
#  upgraded             :boolean          default(FALSE)
#

class Video < ActiveRecord::Base
  include Commentable
  
  extend FriendlyId
  friendly_id :title, use: :slugged

  self.per_page = 30

  belongs_to :specialty
  belongs_to :author
  acts_as_list scope: :specialty

  has_many :questions, dependent: :destroy
  has_many :vimeos, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :nested_comments, as: :root, class_name: "Comment"
  has_many :notes, as: :noteable, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :flashcards

  validates :title, presence: true
  validates :description, presence: true
  validates :specialty_id, presence: true
  validates :duration, presence: true
  validates :vimeo_identifier, presence: true
  validates :file_name, presence: true

  delegate :name, to: :specialty, prefix: true
  delegate :name, to: :author, prefix: true
  delegate :tagline, to: :author, prefix: true
  delegate :twitter, to: :author, prefix: true
  delegate :facebook, to: :author, prefix: true

  after_save :touch_assets

  def has_questions?
    true if questions_count > 0
  end

  def duration_as_string
    "| #{duration} minutes"
  end

  def friendly_publication_date
    "| #{created_at.strftime('%b %y')} "
  end

  def mark_proofread
    questions.each { |q| q.update_attributes(proofread: true) }
  end

  def is_proofread?
    questions.where(proofread: true).count == questions.count ? true : false
  end

  def is_upgraded?
    upgraded
  end

  # Caching functions

  def touch_assets
    notes.each { |note| note.touch }
  end

  def cached_questions_count
    Rails.cache.fetch([self, "questions_count"]) { questions.count }
  end

  # Class functions

  def self.recent
    order(id: :desc)
  end

  def self.flagged(user)
    if user.vimeos.any?
      # temp removed poor_result method until we can make it faster
      unfinished(user.vimeos) | unwatched(user.vimeos) |  self.watched(user.vimeos)
    else
      self.all
    end
  end

  # searches by case insensitive title and tags
  def self.search_with(param)
    videos = Video.where('title ILIKE ?', "%#{param}%") + Video.pessimistic_tagged_with(param)
    videos.uniq
  end

  # Stat functions

  def increment_views
    Video.increment_counter(:views, self.id)
  end

  def question_status
    return "red" if self.questions.count < 7
  end

  # Tags

  def self.tagged_with(name)
    Tag.find_by_name!(name).videos
  end

  def self.pessimistic_tagged_with(name)
    tag = Tag.where(name: name).first
    tag ? tag.videos : []
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  # Notifications

  def send_video_notification
    User.episode_notifications_allowed.each do |user|
      UserMailer.delay.new_episode(user, self)
    end
  end
  handle_asynchronously :send_video_notification

  def send_test_notification
    AdminMailer.delay.new_test_episode(self)
  end

  private

    def self.unfinished(vimeos)
      self.where(id: vimeos.where(completed: false).pluck(:video_id)).includes(:specialty)
    end

    def self.poor_result(vimeos)
      user = User.find_by(id: vimeos.first.user_id)
      id_array = []
      vimeos.includes(:video).each do |vimeo|
        if user.user_questions.where(question_id: vimeo.video.question_ids).any?
          questions = user.user_questions.where(question_id: vimeo.video.question_ids)
          results = QuestionResults.new(questions, vimeo.video.question_ids.count)
          if results.bad_result?
            id_array << vimeo.video_id
          end
        end
      end
      self.where(id: id_array).includes(:specialty)
    end

    def self.unwatched(vimeos)
      self.where.not(id: vimeos.pluck(:video_id))
    end

    def self.watched(vimeos)
      self.where(id: vimeos.where(completed: true).pluck(:video_id)).includes(:specialty)
    end

end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  layout 'admin_application'
  respond_to :html, :json

  before_action :set_video, only: [:show, :edit, :update, :destroy, :move_up, :move_down, 
                                   :send_notifications, :send_test_notifications, :mark_proofread]

  def index
    @q = Video.search(params[:q])
    @videos = apply_scopes(@q.result.includes(:specialty, :tags, :author).order(views: :desc).paginate(page: params[:page]))
  end

  def show
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to admin_video_path(@video), notice: 'New video added'
    else
      render :new
    end
  end

  def update
    if @video.update_attributes(video_params)
      redirect_to admin_video_path(@video), notice: 'Video updated'
    else
      render :edit
    end
  end

  def move_up
    @video.move_higher
    redirect_to admin_specialty_path(@video.specialty)
  end

  def move_down
    @video.move_lower
    redirect_to admin_specialty_path(@video.specialty)
  end

  def send_notifications
    @video.send_video_notification
    redirect_to :back
  end

  def send_test_notifications
    @video.send_test_notification
    redirect_to :back, notice: 'New episode test email sending'
  end

  def mark_proofread
    @video.mark_proofread
    redirect_to :back, notice: 'All questions now marked as proofread'
  end

  private

    def video_params
      params.require(:video).permit(:title, :description, :specialty_id, :vimeo_identifier, :duration, :preview, :file_name, :speaker_name, :position, :author_id, :tag_list, :proofread, :has_slides, :upgraded)
    end

    def set_video
      @video = Video.friendly.find(params[:id])
    end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  layout 'user_application'

  def index
    if params[:tag]
      @videos = Video.includes(:specialty).tagged_with(params[:tag])
    elsif params[:search]
      @videos = Video.includes(:specialty).search_with(params[:search])
    else
      @videos = Video.includes(:specialty).all
    end
  end

  def show
    @video = Video.includes(:specialty, :author, :tags).friendly.find(params[:id])
    @specialty = @video.specialty
    @author = @video.author
    @flashcards = @video.flashcards
    @video.increment_views
    @progress = Vimeo.register_ids(@video.id, current_user)
    @comment = Comment.new(user: current_user)
    @notes = @video.notes.find_by(user: current_user) || Note.new(noteable: @video)
  end

  private

    def check_unlock
      unless current_user.has_access_to?(@specialty) || current_user.admin || @video.preview
        redirect_to @specialty, alert: 'Please unlock this specialty to view videos and questions.'
      end
    end

end

app/helpers/videos_helper.rb
module VideosHelper

  def questions_exist
    @video.questions_count > 0
  end

end

app/views/videos/_author.html.erb
<% cache @author do %>
  <p class="lecture_by_title">Lecture by</p>

  <div class="video_page_authour_right_column_user_info">
    <div class="video_page_authour_right_column_avatar">
      <%= image_tag @author.get_avatar(:square, request), width: '128', height: '128' %>
    </div>
    <div class="video_page_authour_right_column_user_info_inner_wrapper">
      <p class="video_page_authour_right_column_name"><%= @author.name %><p>
      <p class="video_page_authour_right_column_title"><%= @author.tagline %></p>
      <div class="video_page_authour_social_icons_wrapper">
        <% unless @author.twitter.blank? %>
          <%= link_to '', @author.twitter,  class: 'video_page_authour_twitter_icon', target: '_blank' %>
        <% end %>
        <% unless @author.facebook.blank? %>
          <%= link_to '', @author.facebook, class: 'video_page_authour_fb_icon', target: '_blank' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/videos/_downloads.html.erb
<%= link_to "Video file", video_download_video_path(@video), class: 'video_download_dropdown_link video_file_icon', target: '_blank' %>
<%= link_to "Audio File", video_download_audio_path(@video), class: 'video_download_dropdown_link audio_file_icon', target: '_blank' %>
<% if @video.has_slides %>
  <%= link_to "Slides", video_download_slides_path(@video), class: 'video_download_dropdown_link slides_file_icon', target: '_blank' %>
<% else %>
  <%= link_to "Slides unavailable", '#', class: 'video_download_dropdown_link slides_file_icon no_slides' %>
<% end %>

app/views/videos/_tags.html.erb
<% @video.tags.each do |tag| %>
  <%= link_to tag_path(tag.name), class: 'tag' do %>
    <span><%= tag.name %></span>
  <% end %>
<% end %>

app/views/videos/index.html.erb
<div class="inner questions_answers_page">

  <div class="sub_heading_wrapper search_page_header">
    <h1>Search Results</h1>
    <div class="sub_heading_button_set">
      <%= render 'quick_nav' %>
    </div>
  </div>


  <div class="page">
    <div class="speciality_search_page_wrapper">
      <div id="tabs_single_page">
        <% unless @videos.empty? %>

              <p class="search_tab_sub_title">Vidoes that cover this topic:</p>
              <%= render partial: 'dashboards/video_list', locals: {videos: @videos} %>
            </div>

        <% else %>
          <div class="no_search_results_wrapper">
            <p class="no_search_results_found_title">Sorry nothing found for this search</p>
          </div>
        <% end %>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/videos/show.html.erb
<%= content_for(:title) { "Podmedics | #{@video.title}" } %>

<div class="video_page_header">
  <div class="inner video_page">
    <div class="video_page_heading_wrapper">
      <h1><%= @video.title %></h1>
      <p class="video_breadcrumb">
        <%= link_to @specialty.name, specialty_path(@specialty) %>
        /
        <%= link_to @video.title, video_path(@video) %>
      </p>
    </div>

    <div class="video_page_heading_button_set">
      <% if @flashcards.count > 0 %>
        <a href="javascript:;" class="podmedcis_button green flash_cards_button">Flashcards</a>
      <% end %>
      <%= link_to 'Create flashcard', new_video_flashcard_path(@video), class: 'podmedcis_button green flash_cards_button create_card' %>

      <% if current_user.has_subscription_and_in_date? %>
        <div class="video_download_dropdown">
          <a href="#" class="podmedcis_button white_download_button">Download</a>
          <div class="video_download_dropdown_inner">
            <%= render partial: 'downloads' %>
          </div>
        </div>
      <% end %>

      <% if questions_exist %>
        <%= link_to video_questions_url(:video_id => @video.id), class: "podmedcis_button take_exam_button" do %>
          <span id="tour_exam_button">Answer</span> Questions
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="inner_divide_video_wrapper">
  <div class="inner video_page">
    <div class="video_header_outer">

      <div class="video_page_author_duration_header">
        <p><%= @video.description %></p>
      </div>

      <div class="video_page_tags_wrapper">
        <% cache @video do %>
          <%= render @video.tags %>
        <% end %>
      </div>

      <div class="video_header_inner">
        <div class="video_column">
          <div class="vendor">
            <iframe src="https://player.vimeo.com/video/<%= @video.vimeo_identifier %>?api=1&portrait=0&color=fa3f52&player_id=vimeoplayer" width="400" height="225" frameborder="0" id="vimeoplayer"></iframe>
          </div>
        </div>

        <div class="video_page_notes_column">
          <div class="video_page_notes_column_title">
            <strong>Notes</strong>
            <p>Save personal notes for reference later</p>
          </div>
          <div class="video_page_notes_column_divide"></div>
          <%= render partial: 'notes/form' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="inner video_page">
  <div class="page">
    <div class="speciality_left_column">

      <div class="lectures_speciality_outer_wrapper">
        <div id="tabs">
          <ul>
            <li><a href="#tabs-2" title="" class="comments_tab"><p>Comments/Questions (<%= @video.cached_comments_count %>)</p><p class="icon"></p></a></li>
          </ul>

          <div id="tabs_container">
            <div id="tabs-2" class="tab_box">
              <div>
                <div class="questions_answers_main_question video_page_comments_wrapper" >

                  <% if @video.cached_comments_count == 0 %>
                  <div class="no_questions_reply_wrapper">
                    Nothing posted yet.
                    <a href="javascript:;">
                      Be the first to comment.
                    </a>
                  </div>
                  <% end %>

                  <div class="questions_aswer_comment_textarea" id="comment_reply_textarea">
                    <div class="inner_page_padding comments_textarea_wrapper">
                      <%= render partial: 'comments/form', locals: {root: @video} %>
                    </div>
                  </div>

                  <div class="question_comments_outer">
                    <%= render partial: 'comments/comment', collection: @video.cached_comments %>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="video_page_right_column">
      <% if @author %>
        <%= render 'author' %>
      <% end %>

      <div class="video_page_right_column_lower_info">
        <p>Video Duration: <strong><%= @video.duration %> minutes</strong></p>
        <p>Views: <strong><%= @video.views %></strong></p>
        <p>Comments: <strong><%= @video.cached_comments_count %></strong></p>
      </div>
    </div>

    <div class="clear"></div>
  </div>

  <%= content_for :footer do %>
      <%= render 'footer' %>
  <% end %>

</div>

<script id="progress_json" type="text/json">
    <%= raw @progress.to_json %>
</script>


<% if @flashcards.count > 0 %>
    <div class="flashcard_background"></div>
    <div class="flashcard_wrapper">
      <div class="close_flashcard_wrapper">
        <div class="close_flashcard"></div>
      </div>

      <div class="cd-tabs">
        <nav>
          <ul class="cd-tabs-navigation">
            <% @flashcards.each_with_index do |flashcard, index| %>
                <li><a data-content="tab_<%= index %>" class="<%= 'selected' if index == 0 %>" href="#<%= index %>"><%= flashcard.title %></a></li>
            <% end %>
          </ul>
        </nav>

        <ul class="cd-tabs-content">
          <% @flashcards.each_with_index do |flashcard, index| %>
            <li data-content="tab_<%= index %>" class="<%= 'selected' if index == 0 %>">
            <div class="inner_flashcard_wrapper">
              <div class="flashcard_name">
                <%= flashcard.title %>
              </div>
              <div class="flashcard_user_created_name">
                Created by <%= link_to flashcard.user.name, user_path(flashcard.user) %>
              </div>

              <div class="flashcard_divider"></div>

              <div class="flashcard_title">General</div>

              <div class="flashcard_title sub">Epidemiology</div>
              <div class="flashcard_copy">
                <%= flashcard.epidemiology.html_safe %>
              </div>

              <div class="flashcard_title sub">Pathology</div>
              <div class="flashcard_copy">
                <%= flashcard.pathology.html_safe %>
              </div>

              <div class="flashcard_title sub">Top three causes</div>
              <div class="flashcard_copy">
                <%= flashcard.causes.html_safe %>
              </div>

              <div class="flashcard_divider"></div>

              <div class="flashcard_title">Clinical Features</div>

              <div class="flashcard_title sub">Symptoms</div>
              <div class="flashcard_copy">
                <%= flashcard.symptoms.html_safe %>
              </div>

              <div class="flashcard_title sub">Signs</div>
              <div class="flashcard_copy">
                <%= flashcard.signs.html_safe %>
              </div>

              <div class="flashcard_divider"></div>

              <div class="flashcard_title">Investigations</div>
              <div class="flashcard_table_wrapper">
                <table>
                  <tr>
                    <td class="flashcard_table_left_column">Cultures</td>
                    <td><%= flashcard.inv_cultures.html_safe %></td>
                  </tr>
                  <tr>
                    <td class="flashcard_table_left_column">Bloods</td>
                    <td><%= flashcard.inv_bloods.html_safe %></td>
                  </tr>
                  <tr>
                    <td class="flashcard_table_left_column">Imaging</td>
                    <td><%= flashcard.inv_imaging.html_safe %></td>
                  </tr>
                  <tr>
                    <td class="flashcard_table_left_column">Scopic/Biopsy</td>
                    <td><%= flashcard.inv_scopic.html_safe %></td>
                  </tr>
                  <tr>
                    <td class="flashcard_table_left_column">Functional</td>
                    <td><%= flashcard.inv_functional.html_safe %></td>
                  </tr>
                </table>

              </div>
              <div class="flashcard_divider"></div>

              <div class="flashcard_title">Treatment</div>


              <div class="flashcard_title sub">Conservative</div>
              <div class="flashcard_copy">
                <%= flashcard.treat_cons.html_safe %>
              </div>

              <div class="flashcard_title sub">Medical</div>
              <div class="flashcard_copy">
                <%= flashcard.treat_medical.html_safe %>
              </div>

              <div class="flashcard_title sub">Surgical</div>
              <div class="flashcard_copy">
                <%= flashcard.treat_surgical.html_safe %>
              </div>

            </div>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>


<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
    // track video page view
    var title = "<%= @video.title %>";
    mixpanel.track('Video played', {
      "name" : title
    });

    // track hitting the quiz button from here
    mixpanel.track_links("a.take_exam_button", "Click Video Quiz", {
      "name" : title
    });

    analytics.track("Watched video", {
      "name" : title
    });
  });
</script>