config/routes.rb
PodmedicsVictory::Application.routes.draw do

  # Static pages
  root 'static_pages#home'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/faqs', to: 'static_pages#faqs', as: 'faqs'
  get '/library', to: 'static_pages#library', as: 'library'
  get '/terms', to: 'static_pages#terms', as: 'terms'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/support', to: 'static_pages#support', as: 'support'
  get '/press', to: 'static_pages#press', as: 'press'
  get '/app', to: 'static_pages#app', as: 'app'
  get '/quiz_privacy', to: 'static_pages#quiz_privacy', as: 'quiz_privacy'
  resources :courses, only: [:index]
  resources :posts, only: [:index, :show]

  # RSS feed redirects
  match '/Podmedics/Podmedics/rss.xml' => redirect('http://feeds.feedburner.com/podmedics'), via: :get
  match '/feeds/podcasts' => redirect('http://feeds.feedburner.com/podmedics'), :as => :feed, via: :get
  match '/podcasts/rss.rss' => redirect('http://feeds.feedburner.com/podmedics'), via: :get

  # Authentication
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'signup', to: 'users#new', as: :signup
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index] do
    member do
      get 'email'
      get 'move_to_gravatar'
    end
  end

  post 'unsubscribed', to: 'users#unsubscribed', as: :unsub
  get 'unsubscribe', to: 'users#unsubscribe'
  get 'unsubscribe/:unsubscribe_token', to: 'users#unsubscribe', as: :unsubscribe_token

  resources :password_resets, only: [:create, :edit, :update]

  # Omniauth
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: 'sessions#new', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  # Transactions/Stripe Events
  get ':user_id/buy', to: 'transactions#new', as: :show_buy
  post ':user_id/buy/:permalink', to: 'transactions#create', as: :buy
  get ':user_id/pickup', to: 'transactions#pickup', as: :pickup
  get '/receive_paypal', to: 'transactions#receive_paypal', as: :receive_paypal
  get ':user_id/cancel_transaction', to: 'transactions#cancel_transaction', as: :cancel_transaction
  resources :stripe_events, only: [:create]
  resources :sales, only: [:show]

  # Dashboards and admin
  match '/admin' => redirect('/admin/dashboard'), via: :get
  resource :dashboard, only: :show
  namespace :admin do
    resource :dashboard, only: :show
    resources :categories, except: :delete
    resources :specialties
    resources :questions, only: [:index]
    resources :videos, except: :delete do
      member do
        get 'move_up'
        get 'move_down'
        get 'send_notifications'
        get 'send_test_notifications'
        get 'mark_proofread'
      end
      resources :questions, except: [:index] do
        member do
          get 'mark_proofread'
        end
      end
    end
    resources :flashcards do
      member do
        get 'approve'
      end
    end
    resources :users do
      member { get 'send_1w_reminder'}
      collection { get 'remove_if_no_plan'}
    end
    resources :authors
    resources :faqs
    resources :courses
    resources :questions
    resources :products
    resources :sales, only: [:index, :show]
    resources :newsletters do
      member do
        get 'send_test'
        get 'send_newsletter'
      end
    end
    resources :posts
    resources :comments, except: [:show]
    resources :badges
    resources :quizes
    resources :notes, only: [:index, :show]
  end

  # Specialty/Video
  resources :videos, only: [:show, :index] do
    resources :flashcards, only: [:new, :create]
    resources :questions, only: :index
    get 'video', to: 'hosted_files#video', as: 'download_video'
    get 'audio', to: 'hosted_files#audio', as: 'download_audio'
    get 'slides', to: 'hosted_files#slides', as: 'download_slides'
  end
  get 'tags/:tag', to: 'videos#index', as: :tag
  match 'questions/answer', to: 'questions#answer', via: [:get, :post]
  get 'questions/result', to: 'questions#result'
  get 'questions/general', to: 'questions#general_index'
  resources :questions, only: :show

  resources :specialties, only: [:show] do
    resources :questions, controller: :specialty_questions, as: :questions
    get 'questions/load/:page', to: 'specialty_questions#load', as: :question_load
    resources :specialty_unlocks, only: [:create]
  end

  get 'specialties/:id/exam', to: 'questions#specialty_index', as: :specialty_exam

  resources :comments do
    member do
      get 'vote'
      get 'accept'
    end
  end

  resources :notes, only: [:create, :update, :show, :index] do
    get 'load', on: :member
  end
  get 'notes/specialty/:specialty_id', to: 'notes#index', as: :specialty_notes
  get 'notes/category/:category_id', to: 'notes#index', as: :category_notes

  # VimeosController
  get 'vimeos/completed', to: 'vimeos#completed', as: :vimeos_completed
  get 'vimeos/paused', to: 'vimeos#paused', as: :vimeos_paused

  # API

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :specialties
      resources :questions do
        collection do
          get 'count'
          get 'sample'
        end
      end
    end
  end

end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id                   :integer          not null, primary key
#  title                :string(255)
#  description          :text
#  specialty_id         :integer
#  vimeo_identifier     :string(255)
#  duration             :integer
#  created_at           :datetime
#  updated_at           :datetime
#  preview              :boolean          default(FALSE)
#  slug                 :string(255)
#  speaker_name         :string(255)
#  views                :integer          default(0)
#  file_name            :string(255)
#  questions_count      :integer          default(0), not null
#  position             :integer
#  author_id            :integer
#  slide_download_count :integer
#  audio_download_count :integer
#  video_download_count :integer
#  proofread            :boolean          default(FALSE)
#  has_slides           :boolean          default(TRUE)
#  upgraded             :boolean          default(FALSE)
#

class Video < ActiveRecord::Base
  include Commentable
  
  extend FriendlyId
  friendly_id :title, use: :slugged

  self.per_page = 30

  belongs_to :specialty
  belongs_to :author
  acts_as_list scope: :specialty

  has_many :questions, dependent: :destroy
  has_many :vimeos, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :nested_comments, as: :root, class_name: "Comment"
  has_many :notes, as: :noteable, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :flashcards

  validates :title, presence: true
  validates :description, presence: true
  validates :specialty_id, presence: true
  validates :duration, presence: true
  validates :vimeo_identifier, presence: true
  validates :file_name, presence: true

  delegate :name, to: :specialty, prefix: true
  delegate :name, to: :author, prefix: true
  delegate :tagline, to: :author, prefix: true
  delegate :twitter, to: :author, prefix: true
  delegate :facebook, to: :author, prefix: true

  after_save :touch_assets

  def has_questions?
    true if questions_count > 0
  end

  def duration_as_string
    "| #{duration} minutes"
  end

  def friendly_publication_date
    "| #{created_at.strftime('%b %y')} "
  end

  def mark_proofread
    questions.each { |q| q.update_attributes(proofread: true) }
  end

  def is_proofread?
    questions.where(proofread: true).count == questions.count ? true : false
  end

  def is_upgraded?
    upgraded
  end

  # Caching functions

  def touch_assets
    notes.each { |note| note.touch }
  end

  def cached_questions_count
    Rails.cache.fetch([self, "questions_count"]) { questions.count }
  end

  # Class functions

  def self.recent
    order(id: :desc)
  end

  def self.flagged(user)
    if user.vimeos.any?
      # temp removed poor_result method until we can make it faster
      unfinished(user.vimeos) | unwatched(user.vimeos) |  self.watched(user.vimeos)
    else
      self.all
    end
  end

  # searches by case insensitive title and tags
  def self.search_with(param)
    videos = Video.where('title ILIKE ?', "%#{param}%") + Video.pessimistic_tagged_with(param)
    videos.uniq
  end

  # Stat functions

  def increment_views
    Video.increment_counter(:views, self.id)
  end

  def question_status
    return "red" if self.questions.count < 7
  end

  # Tags

  def self.tagged_with(name)
    Tag.find_by_name!(name).videos
  end

  def self.pessimistic_tagged_with(name)
    tag = Tag.where(name: name).first
    tag ? tag.videos : []
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  # Notifications

  def send_video_notification
    User.episode_notifications_allowed.each do |user|
      UserMailer.delay.new_episode(user, self)
    end
  end
  handle_asynchronously :send_video_notification

  def send_test_notification
    AdminMailer.delay.new_test_episode(self)
  end

  private

    def self.unfinished(vimeos)
      self.where(id: vimeos.where(completed: false).pluck(:video_id)).includes(:specialty)
    end

    def self.poor_result(vimeos)
      user = User.find_by(id: vimeos.first.user_id)
      id_array = []
      vimeos.includes(:video).each do |vimeo|
        if user.user_questions.where(question_id: vimeo.video.question_ids).any?
          questions = user.user_questions.where(question_id: vimeo.video.question_ids)
          results = QuestionResults.new(questions, vimeo.video.question_ids.count)
          if results.bad_result?
            id_array << vimeo.video_id
          end
        end
      end
      self.where(id: id_array).includes(:specialty)
    end

    def self.unwatched(vimeos)
      self.where.not(id: vimeos.pluck(:video_id))
    end

    def self.watched(vimeos)
      self.where(id: vimeos.where(completed: true).pluck(:video_id)).includes(:specialty)
    end

end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  layout 'admin_application'
  respond_to :html, :json

  before_action :set_video, only: [:show, :edit, :update, :destroy, :move_up, :move_down, 
                                   :send_notifications, :send_test_notifications, :mark_proofread]

  def index
    @q = Video.search(params[:q])
    @videos = apply_scopes(@q.result.includes(:specialty, :tags, :author).order(views: :desc).paginate(page: params[:page]))
  end

  def show
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to admin_video_path(@video), notice: 'New video added'
    else
      render :new
    end
  end

  def update
    if @video.update_attributes(video_params)
      redirect_to admin_video_path(@video), notice: 'Video updated'
    else
      render :edit
    end
  end

  def move_up
    @video.move_higher
    redirect_to admin_specialty_path(@video.specialty)
  end

  def move_down
    @video.move_lower
    redirect_to admin_specialty_path(@video.specialty)
  end

  def send_notifications
    @video.send_video_notification
    redirect_to :back
  end

  def send_test_notifications
    @video.send_test_notification
    redirect_to :back, notice: 'New episode test email sending'
  end

  def mark_proofread
    @video.mark_proofread
    redirect_to :back, notice: 'All questions now marked as proofread'
  end

  private

    def video_params
      params.require(:video).permit(:title, :description, :specialty_id, :vimeo_identifier, :duration, :preview, :file_name, :speaker_name, :position, :author_id, :tag_list, :proofread, :has_slides, :upgraded)
    end

    def set_video
      @video = Video.friendly.find(params[:id])
    end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  layout 'user_application'

  def index
    if params[:tag]
      @videos = Video.includes(:specialty).tagged_with(params[:tag])
    elsif params[:search]
      @videos = Video.includes(:specialty).search_with(params[:search])
    else
      @videos = Video.includes(:specialty).all
    end
  end

  def show
    @video = Video.includes(:specialty, :author, :tags).friendly.find(params[:id])
    @specialty = @video.specialty
    @author = @video.author
    @flashcards = @video.flashcards
    @video.increment_views
    @progress = Vimeo.register_ids(@video.id, current_user)
    @comment = Comment.new(user: current_user)
    @notes = @video.notes.find_by(user: current_user) || Note.new(noteable: @video)
  end

  private

    def check_unlock
      unless current_user.has_access_to?(@specialty) || current_user.admin || @video.preview
        redirect_to @specialty, alert: 'Please unlock this specialty to view videos and questions.'
      end
    end

end

app/helpers/videos_helper.rb
module VideosHelper

  def questions_exist
    @video.questions_count > 0
  end

end

app/views/admin/videos/_form.html.erb
<div class="row form-wrapper">
  <div class="col-md-6">
    <%= simple_form_for [:admin, @video] do |f| %>
      <%= f.error_notification %>
      <%= f.input :position %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :tag_list, as: :text, hint: 'tags separated by commas' %>
      <%= f.association :specialty, as: :select, collection: Specialty.all.order(:name) %>
      <%= f.association :author, as: :select, collection: Author.all.order(:name) %>
      <%= f.input :vimeo_identifier, label: 'Vimeo Identifier' %>
      <%= f.input :file_name, label: 'Download file name' %>
      <%= f.input :has_slides, hint: 'Does this video have slides available?' %>
      <%= f.input :duration %>
      <%= f.input :speaker_name %>
      <%= f.input :preview  %>
      <%= f.input :proofread %>
      <%= f.input :upgraded %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/admin/videos/_video.html.erb
<tr class="video <%= video.question_status %>">
  <td><%= video.id %></td>
  <td><%= link_to video.title, admin_video_path(video) %></td>
  <td><%= link_to video.specialty_name, admin_specialty_path(video.specialty) %></td>
  <td><%= video.views %></td>
  <td><%= video.questions_count %></td>
  <td><%= video.tag_list %></td>
  <td><%= video.is_proofread? %></td>
  <td><%= video.upgraded? %></td>
  <td style="width: 140px;">
    <ul class="actions">
      <li><%= link_to "Edit", edit_admin_video_path(video) %></li>
      <li><%= link_to "Show", admin_video_path(video) %></li>
    </ul>
  </td>
</tr>

app/views/admin/videos/edit.html.erb
<div class="row header">
  <div class="col-md-12">
    <h3>Edit Video</h3>
  </div>
</div>

<%= render 'form' %>

app/views/admin/videos/index.html.erb
<div class="row header">
  <h3>Videos</h3>
  <div class="col-md-10 col-sm-10 col-xs-10 pull-right">
    <%= link_to "New video", new_admin_video_path, class: 'btn-flat success pull-right' %>
    <%= link_to "View all", admin_videos_path, class: 'btn-flat success pull-right grey' %>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <%= search_form_for @q, url: admin_videos_path do |f| %>
      <%= f.search_field :title_cont, placeholder: 'Search by title...', class: 'search' %>
      <%= f.submit 'Search', class: 'btn-flat' %>
    <% end %>
  </div>
</div>

<%= will_paginate @videos %>

<div class="row">
  <div class="col-md-12">
    <div class="table-wrapper">
      <table class='table table-hover table-striped' border="0">
        <thead>
          <tr>
            <%= content_tag :th, sort_link(@q, :id) %>
            <%= content_tag :th, sort_link(@q, :title) %>
            <th>Specialty</th>
            <%= content_tag :th, sort_link(@q, :views) %>
            <th>Questions</th>
            <th>Tags</th>
            <%= content_tag :th, sort_link(@q, :is_proofread?) %>
            <%= content_tag :th, sort_link(@q, :upgraded?) %>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render @videos %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= will_paginate @videos %>

app/views/admin/videos/new.html.erb
<div class="row header">
  <div class="col-md-12">
    <h3>New Video</h3>
  </div>
</div>

<%= render 'form' %>

app/views/admin/videos/show.html.erb
<div class="page-header">
  <h1>
    <%= @video.title  %>
  </h1>
  <div class="admin_video_buttons_title_block">
    <%= link_to "Edit", edit_admin_video_path(@video), class: 'btn-flat success' %>
    <%= link_to 'View on frontend', video_path(@video), class: 'btn-flat success' %>
    <%= link_to "Mark proofread", mark_proofread_admin_video_path(@video), class: 'btn-flat success' %>
    <%= link_to 'Send test notification', send_test_notifications_admin_video_path(@video), class: 'btn-flat success' %>
    <%= link_to 'Send email notifications', send_notifications_admin_video_path(@video), data: { confirm: 'Are you sure'}, class: 'btn-flat success' %>
    <%= link_to "Back to #{@video.specialty.name}", admin_specialty_path(@video.specialty), class: 'btn-flat success grey' %>
    <%= link_to "View all", admin_videos_path, class: 'btn-flat success grey' %>
  </div>
</div>

  <div class="stats_blocks_wrapper">

    <div class="stats_block">
      <p class="title"><%= @video.views %></p>
      <p class="sub_title">Views</p>
    </div>


    <div class="stats_block">
      <p class="title"><%= @video.duration %></p>
      <p class="sub_title">Duration</p>
    </div>


    <div class="stats_block">
      <p class="title"><%= @video.has_slides %></p>
      <p class="sub_title">Has Slides</p>
    </div>


    <div class="stats_block">
      <p class="title"><%= @video.preview %></p>
      <p class="sub_title">Preview</p>
    </div>


    <div class="stats_block">
      <p class="title"><%= @video.is_upgraded? ? 'YES' : 'NO' %></p>
      <p class="sub_title">Upgraded</p>
    </div>


    <div class="stats_block">
      <p class="title"><%= @video.is_proofread? ? 'YES' : 'NO' %></p>
      <p class="sub_title">Proofread</p>
    </div>

  </div>








<div class="row admin_clear_fix">
  <div class="col-md-12">
    <iframe src="https://player.vimeo.com/video/<%= @video.vimeo_identifier %>?portrait=0&color=fa3f52" width="800px" height="400px" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
  </div>
  <div class="col-md-12">    <br><br>
    <div class="well">

      <p>Created at: <%= @video.created_at.to_s(:long) %></p>
      <p>Updated at: <%= @video.updated_at.to_s(:long) %></p>
      <p>Description: <%= @video.description %></p>
      <p>Tags: <%= @video.tag_list %></p>
      <p>Speaker: <%= @video.speaker_name %></p>
      <% if @video.author %>
        <p>Author: <%= link_to @video.author.name, admin_author_path(@video.author) %></p>
      <% end %>
      <p>File: <%= @video.file_name %></p>
      <p>Has slides: <%= @video.has_slides %></p>
    </div>

    <% if @video.has_slides %>
      <div class="downloads">
        <a href="http://podmedics-resources.s3.amazonaws.com/slides/<%= @video.file_name %>.pdf" class="btn btn-primary btn-xs", target="_blank">Download pdf</a>
      </div>
    <% end %>
  </div>


</div>

<h2>
  Questions
  <small>
    <%= link_to "Add question", new_admin_video_question_path(@video) %>
  </small>
</h2>
<p>Total: <%= @video.questions_count %></p>
<hr />

<div class="questions">
  <%= render @video.questions.order(:id) %>
</div>